# Generated by Django 4.1.2 on 2022-10-19 17:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Druzyna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('kraj', models.CharField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('US', 'Stany Zjednoczone')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('miesiac', models.CharField(choices=[(1, 'Styczen'), (2, 'Luty'), (3, 'Marzec'), (4, 'Kwiecień'), (5, 'Maj'), (6, 'Czerwiec'), (7, 'Lipiec'), (8, 'Sierpień'), (9, 'Wrzesień'), (10, 'Październik'), (11, 'Listopad'), (12, 'Grudzień')], default=1, max_length=2)),
                ('data_dodania', models.DateField(verbose_name=datetime.datetime(2022, 10, 19, 19, 54, 25, 705634))),
                ('druzyna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appka.druzyna')),
            ],
            options={
                'ordering': ['nazwisko'],
            },
        ),
    ]
