# Generated by Django 4.1.2 on 2022-10-19 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druzyna',
            name='kraj',
            field=models.CharField(choices=[('PL', 'Polska'), ('US', 'Stany Zjednoczone'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('EN', 'Anglia')], max_length=2),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 20, 4, 2, 980174)),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='miesiac',
            field=models.CharField(choices=[('1', 'STYCZEN'), ('2', 'LUTY'), ('3', 'MARZEC'), ('4', 'KWIECIEN'), ('5', 'MAJ')], default='1', max_length=2),
        ),
    ]
