# Generated by Django 4.1.2 on 2022-10-19 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appka', '0002_alter_druzyna_kraj_alter_osoba_data_dodania_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 20, 5, 5, 584704)),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='miesiac',
            field=models.CharField(choices=[('1', 'STYCZEN'), ('2', 'LUTY'), ('3', 'MARZEC'), ('4', 'KWIECIEN'), ('5', 'MAJ'), ('6', 'CZERWIEC'), ('7', 'LIPIEC'), ('8', 'SIERPIEN'), ('9', 'WRZESIEN'), ('10', 'PAZDZIERNIK'), ('11', 'LISTOPAD'), ('12', 'GRUDZIEN')], default='1', max_length=2),
        ),
    ]
