# Generated by Django 4.1.2 on 2022-10-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kebab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priceSMALL', models.DecimalField(decimal_places=2, max_digits=4)),
                ('priceBIG', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priceSMALL', models.DecimalField(decimal_places=2, max_digits=4)),
                ('priceBIG', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
